=== AndreiLysko/A.Lysko/Task7/src/com/epam/menu-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema 	xmlns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.task7.org/menu-schema"
           xmlns:tns="http://www.task7.org/menu-schema"
           elementFormDefault="qualified">

    <element name="menu">
        <complexType>
            <sequence>
                <element name="menuPage" type="tns:dishType" minOccurs="1" maxOccurs="12"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="dishType">
        <sequence>
            <element name="dish"  type="tns:dish" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>

        <attribute name="dishTypeName" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="coldSnack"></enumeration>
                    <enumeration value="hotSnack"></enumeration>
                    <enumeration value="breakfast"></enumeration>
                    <enumeration value="salads"></enumeration>
                    <enumeration value="soups"></enumeration>
                    <enumeration value="fish meal"></enumeration>
                    <enumeration value="meat meal"></enumeration>
                    <enumeration value="garnish"></enumeration>
                    <enumeration value="grill meal"></enumeration>
                    <enumeration value="from Chef"></enumeration>
                    <enumeration value="addons"></enumeration>
                    <enumeration value="dessert"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="dish" >
        <sequence>
            <element name="photo" type="anyURI"/>
            <element name="title" type="string"/>
            <element name="weight" type="string"/>
            <element name="variations" type="tns:variations"/>
        </sequence>
    </complexType>

    <complexType name="variations">
        <sequence>
            <element name="variation" type="tns:variation" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="variation">
        <sequence>
            <element name="title" type="string"/>
            <element name="price" type="int" default="0"/>
        </sequence>
    </complexType>

</schema>

=== AndreiLysko/A.Lysko/Task7/src/com/epam/menu-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.task7.org/menu-schema"
      xsi:schemaLocation="http://www.task7.org/menu-schema menu-schema.xsd">


    <menuPage dishTypeName="coldSnack">

        <dish>

            <photo>http://www.task7.org/1.jpg</photo>
            <title>Ассорти рыбное</title>
            <weight>100/20/15</weight>
            <variations>
                <variation>
                    <title>Слабосоленая форель, семга</title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/2.jpg</photo>
            <title>Тарталетки с красной икрой</title>
            <weight>60/50</weight>
            <variations>
                <variation>
                    <title>Тарталетки с красной икрой</title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/3.jpg</photo>
            <title>Закуска по-русски</title>
            <weight>70/50/2/10</weight>
            <variations>
                <variation>
                    <title>Кусочки атлантической сельди с отварным картофелем, луком, лимоном и зеленью</title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/4.jpg</photo>
            <title>Куриный рулет</title>
            <weight>100/5</weight>
            <variations>
                <variation>
                    <title>Куриный рулет собственного производства</title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/5.jpg</photo>
            <title>Бастурма</title>
            <weight>50/5</weight>
            <variations>
                <variation>
                    <title>Слабосоленая форель, семга</title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/6.jpg</photo>
            <title>Ассорти мясное</title>
            <weight>100/30</weight>
            <variations>
                <variation>
                    <title>Нарезка из буженины, бастурмы, куринного рулета собственного производства и колбасы</title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/7.jpg</photo>
            <title>Язык отварной</title>
            <weight>80/20/1</weight>
            <variations>
                <variation>
                    <title>Нарезка нежного говяжьего языка, подается с хреном</title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/8.jpg</photo>
            <title>Ассорти баклажаны</title>
            <weight>100/5</weight>
            <variations>
                <variation>
                    <title>Жареные баклажаны с помидорами</title>
                    <price>1</price>
                </variation>
                <variation>
                    <title>Жареные баклажаны с чесноком</title>
                    <price>2</price>
                </variation>
                <variation>
                    <title>Жареные баклажаны с орехами</title>
                    <price>3</price>
                </variation>
            </variations>

        </dish>

    </menuPage>

    <menuPage dishTypeName="hotSnack">

        <dish>

            <photo>http://www.task7.org/9.jpg</photo>
            <title>Лобио с шампиньонами</title>
            <weight>150/5</weight>
            <variations>
                <variation>
                    <title>Фасоль с шампиньонами и грецкими орехами</title>
                    <price>105</price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/10.jpg</photo>
            <title>Жульен</title>
            <weight>120/1</weight>
            <variations>
                <variation>
                    <title>С курицей</title>
                    <price>145</price>
                </variation>
                <variation>
                    <title>С грибами</title>
                    <price>155</price>
                </variation>
            </variations>

        </dish>

    </menuPage>

    <menuPage dishTypeName="breakfast">

        <dish>

            <photo>http://www.task7.org/11.jpg</photo>
            <title>Глазунья</title>
            <weight>150</weight>
            <variations>
                <variation>
                    <title>С ветчиной</title>
                    <price></price>
                </variation>
                <variation>
                    <title>С сыром</title>
                    <price></price>
                </variation>
                <variation>
                    <title>С помидорами</title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/12.jpg</photo>
            <title>Омлет</title>
            <weight>100</weight>
            <variations>
                <variation>
                    <title></title>
                    <price></price>
                </variation>
            </variations>

        </dish>

        <dish>

            <photo>http://www.task7.org/13.jpg</photo>
            <title>Блинчики с мясом</title>
            <weight>150</weight>
            <variations>
                <variation>
                    <title>Жаренные блинчики с мясом</title>
                    <price>145</price>
                </variation>
            </variations>

        </dish>

    </menuPage>

</menu>

=== AndreiLysko/A.Lysko/Task7/src/com/epam/menu.xml
<?xml version="1.0" encoding="UTF-8"?>

<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.task7.com/menu-schema"
      xsi:schemaLocation="http://www.task7.com/menu-schema menu-schema.xsd">

    <menuPage pageType="cold_snacks">
        <dish>
            <photo>1.jpj</photo>
            <title>Ассорти рыбное</title>
            <weight>100/20/15</weight>
            <variations>
                <variation>
                    <title>Слабосолёная форель, сёмга</title>
                    <price/>
                </variation>
            </variations>
        </dish>
        <dish>
            <photo>2.jpg</photo>
            <title>Тарталетки с красной икрой</title>
            <weight>60/50</weight>
            <variations>
                <variation>
                    <title>Тарталетки с красной икрой</title>
                    <price/>
                </variation>
            </variations>
        </dish>
        <dish>
            <photo>3.jpg</photo>
            <title>Закуска по-русски</title>
            <weight>70/50/2/10</weight>
            <variations>
                <variation>
                    <title>Кусочки атлантической сельди с отварным картофелем,
                        луком, лимоном и зеленью
                    </title>
                    <price/>
                </variation>
            </variations>
        </dish>
        <dish>
            <photo>4.jpg</photo>
            <title>Куринный рулет</title>
            <weight>105/5</weight>
            <variations>
                <variation>
                    <title>Куринный рулет собственного производства</title>
                    <price/>
                </variation>
            </variations>
        </dish>
        <dish>
            <photo>5.jpg</photo>
            <title>Бастурма</title>
            <weight>50/5</weight>
            <variations>
                <variation>
                    <title>Вяленая вырезка из говяжьего мяса</title>
                    <price/>
                </variation>
            </variations>
        </dish>
        <dish>
            <photo>6.jpg</photo>
            <title>Ассорти мясное</title>
            <weight>100/30</weight>
            <variations>
                <variation>
                    <title>
                        Нарезка из буженины, бастурмы,
                        куриного рулета собственного производства
                        и колбасы
                    </title>
                    <price/>
                </variation>
            </variations>
        </dish>
        <dish>
            <photo>7.jpg</photo>
            <title>Язык отварной</title>
            <weight>80/20/1</weight>
            <variations>
                <variation>
                    <title>
                        Нарезка нежного говяжьего языка, подаётся
                        с хреном
                    </title>
                    <price/>
                </variation>
            </variations>
        </dish>
        <dish>
            <photo>8.jpg</photo>
            <title>Ассорти баклажаны</title>
            <weight>100/5</weight>
            <variations>
                <variation>
                    <title>Жаренные баклажаны с помидорами</title>
                    <price>1</price>
                </variation>
                <variation>
                    <title>Жаренные баклажаны с чесноком</title>
                    <price>2</price>
                </variation>
                <variation>
                    <title>Жаренные баклажаны с орехами</title>
                    <price>3</price>
                </variation>
            </variations>
        </dish>

    </menuPage>

    <menuPage pageType="hot_snacks">

        <dish>
            <photo>9.jpg</photo>
            <title>Лобио с шампиньонами</title>
            <weight>150/5</weight>
            <variations>
                <variation>
                    <title>Фасоль с шампиньонами и грецким орехом</title>
                    <price>105</price>
                </variation>
            </variations>
        </dish>

        <dish>
            <photo>10.jpg</photo>
            <title>Жульен</title>
            <weight>120/1</weight>
            <variations>
                <variation>
                    <title>Жульен с курицей</title>
                    <price>145</price>
                </variation>
                <variation>
                    <title>Жульен с грибами</title>
                    <price>155</price>
                </variation>
            </variations>
        </dish>

        <dish>
            <photo>11.jpg</photo>
            <title>Креветки</title>
            <weight>120/30</weight>
            <variations>
                <variation>
                    <title>Креветки отварные</title>
                    <price>135</price>
                </variation>
                <variation>
                    <title>Креветки жаренные</title>
                    <price>155</price>
                </variation>
            </variations>
        </dish>

    </menuPage>


    <menuPage pageType="breakfasts">
        <dish>
            <photo>12.jpg</photo>
            <title>Глазунья</title>
            <weight>150</weight>
            <variations>
                <variation>
                    <title>2 яйца (на выбор: ветчина, сыр, помидор)</title>
                    <price/>
                </variation>
            </variations>
        </dish>

        <dish>
            <photo>13.jpg</photo>
            <title>Омлет</title>
            <weight>100</weight>
            <variations>
                <variation>
                    <title></title>
                    <price/>
                </variation>
            </variations>
        </dish>

        <dish>
            <photo>12.jpg</photo>
            <title>Блинчики с мясом</title>
            <weight>150</weight>
            <variations>
                <variation>
                    <title>Жаренные блинчики с мясом</title>
                    <price/>
                </variation>
            </variations>
        </dish>

    </menuPage>

</menu>
