=== AndreiLysko/A.Lysko/Last/out/production/Testing_Module/by/tc/tm/tests/xml/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.testmodule.org/data"
        xmlns:tns="http://www.testmodule.org/data" elementFormDefault="qualified">

    <element name="tests">
        <complexType>
            <sequence>
                <element name="positive_test" type="tns:data" minOccurs="1"
                         maxOccurs="10" />
                <element name="negative_test" type="tns:data" minOccurs="1"
                         maxOccurs="10" />
            </sequence>
        </complexType>
    </element>

    <complexType name="data">
        <sequence>

            <element name="userID" type="int" />
            <element name="login" type="string" />
            <element name="password" type="string" />
            <element name="subjectID" type="int" />
            <element name="subjectName" type="string" />
            <element name="question" type="string" />
            <element name="answerNumber" type="int" />
            <element name="points" type="int" />

        </sequence>

        <attribute name="id" use="required">
        </attribute>

    </complexType>


</schema>

=== AndreiLysko/A.Lysko/Last/out/production/Testing_Module/data.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tests  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.testmodule.org/data"
        xsi:schemaLocation="http://www.testmodule.org/data data.xsd">
    <positive_test id="1">
        <userID>3</userID>
        <login>tutoreen</login>
        <password>tutoreenpass</password>
        <subjectID>1</subjectID>
        <subjectName>english</subjectName>
        <question>How much is the fish?
        1. 12
        2. nanananananaaa
        3. 0</question>
        <answerNumber>2</answerNumber>
        <points>15</points>
    </positive_test>

    <positive_test id="2">
        <userID>2</userID>
        <login>Maloi</login>
        <password>123</password>
        <subjectID>2</subjectID>
        <subjectName>math</subjectName>
        <question></question>
        <answerNumber>0</answerNumber>
        <points>0</points>

    </positive_test>

    <negative_test id="1">
        <userID>2</userID>
        <login></login>
        <password>gydds</password>
        <subjectID>-1</subjectID>
        <subjectName></subjectName>
        <question>Wow?</question>
        <answerNumber>3</answerNumber>
        <points>-1</points>
    </negative_test>
</tests>
